root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "tmp/main"
  cmd = "rm -rf ./tmp & rm -rf ./.parcel-cache & rm -rf ./dist & npx parcel build --dist-dir dist --no-content-hash && templ generate && go build -o ./tmp/main ./main.go"
  # cmd = "go build -o ./tmp/main ./cmd/website/main.go"
  delay = 1000
  exclude_dir = ["node_modules","dist","tmp",".pracel-cache"]
  exclude_file = []
  exclude_regex = ["_test.go","_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  # include_dir = ["cmd", "pkg", "src", "."]
  include_ext = ["go", "templ","html","js"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
